apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared project for platform GitOps applications.
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: demo-platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
