apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: demo-platform
spec:
  selector:
    app: demo-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
