apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  environment: dev

images:
  - name: cloudtf-demo
    newName: example.azurecr.io/cloudtf-demo
    newTag: latest
